# GenerateHelper.cmake
# 由 CMake build 时调用，生成聚合头文件 slang_kernels.h
# 参数：
#   -D OUTPUT=<path>          — 输出文件的完整路径
#   -D INCLUDES_STR=<a|b|c>  — 以 | 分隔的头文件名列表（避免 CMake list 用 ; 引发的转义问题）

string(REPLACE "|" ";" INCLUDES "${INCLUDES_STR}")

file(WRITE "${OUTPUT}"
"#pragma once\n"
"// Auto-generated by CMake — DO NOT EDIT\n"
"// Include all Slang-generated kernel headers\n"
"\n"
)

foreach(inc ${INCLUDES})
    file(APPEND "${OUTPUT}" "#include \"${inc}\"\n")
endforeach()
