# GenerateSlangKernelsH.cmake
# 在构建期生成 slang_kernels.h 聚合头文件
# 参数：
#   -D OUTPUT=<path>           — 输出文件的完整路径
#   -D KERNEL_NAMES=<a|b|c>    — 以 | 分隔的 kernel 名称列表

# 将 | 分隔的字符串转换为 CMake 列表
string(REPLACE "|" ";" KERNEL_NAMES "${KERNEL_NAMES}")

# 写入文件头
file(WRITE "${OUTPUT}"
"#pragma once
// Auto-generated by CMake — DO NOT EDIT
// Include all Slang-generated kernel headers

")

# 包含所有 kernel 的头文件
foreach(_name ${KERNEL_NAMES})
    file(APPEND "${OUTPUT}" "#include \"${_name}.h\"\n")
    file(APPEND "${OUTPUT}" "#include \"${_name}_cpu.h\"\n")
endforeach()

# 生成枚举
file(APPEND "${OUTPUT}" "\nenum class SlangKernelID {\n")
set(_idx 0)
foreach(_name ${KERNEL_NAMES})
    file(APPEND "${OUTPUT}" "    ${_name} = ${_idx},\n")
    math(EXPR _idx "${_idx} + 1")
endforeach()
file(APPEND "${OUTPUT}" "    Count = ${_idx}\n")
file(APPEND "${OUTPUT}" "};\n\n")

# 生成名称字符串表
file(APPEND "${OUTPUT}"
"#ifndef SLANG_KERNEL_NAMES_IMPL
extern const char* const slang_kernel_names[];
#else
const char* const slang_kernel_names[] = {
")
foreach(_name ${KERNEL_NAMES})
    file(APPEND "${OUTPUT}" "    \"${_name}\",\n")
endforeach()
file(APPEND "${OUTPUT}"
"};
#endif // SLANG_KERNEL_NAMES_IMPL
")

# 包含 KernelFactory 特化头文件
file(APPEND "${OUTPUT}" "\n// KernelFactory specializations (generated by SlangCompiler)\n")
foreach(_name ${KERNEL_NAMES})
    file(APPEND "${OUTPUT}" "#include \"${_name}_factory.h\"\n")
endforeach()