#include <slang.h>
#include <slang-com-ptr.h>

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
#include <fstream>

// NVRTC：仅在 CMake 检测到 CUDAToolkit 时启用
#ifdef SLANG_COMPILER_HAS_CUDA
#  include <nvrtc.h>
#endif

// ── CUDA source → PTX（via NVRTC API）────────────────────────────────────────
#ifdef SLANG_COMPILER_HAS_CUDA

static std::vector<uint8_t> compileToPTX(const std::vector<uint8_t>& cudaSrc,
                                          const char* arch)
{
    std::string src(reinterpret_cast<const char*>(cudaSrc.data()), cudaSrc.size());

    nvrtcProgram prog = nullptr;
    nvrtcResult  res  = nvrtcCreateProgram(&prog, src.c_str(), "kernel.cu",
                                            0, nullptr, nullptr);
    if (res != NVRTC_SUCCESS)
    {
        fprintf(stderr, "[SlangCompiler] nvrtcCreateProgram failed: %s\n",
                nvrtcGetErrorString(res));
        return {};
    }

    std::string archOpt = std::string("--gpu-architecture=") + arch;
    const char* opts[]  = { archOpt.c_str(), "--std=c++17" };

    res = nvrtcCompileProgram(prog, 2, opts);
    if (res != NVRTC_SUCCESS)
    {
        size_t logSize = 0;
        nvrtcGetProgramLogSize(prog, &logSize);
        std::string log(logSize, '\0');
        nvrtcGetProgramLog(prog, &log[0]);
        fprintf(stderr, "[SlangCompiler] NVRTC compile error:\n%s\n", log.c_str());
        nvrtcDestroyProgram(&prog);
        return {};
    }

    size_t ptxSize = 0;
    nvrtcGetPTXSize(prog, &ptxSize);
    std::vector<uint8_t> ptx(ptxSize);
    nvrtcGetPTX(prog, reinterpret_cast<char*>(ptx.data()));

    nvrtcDestroyProgram(&prog);
    return ptx;
}

#endif // SLANG_COMPILER_HAS_CUDA

// ── 头文件生成 ────────────────────────────────────────────────────────────────

struct KernelBlob
{
    std::string          targetName;
    std::vector<uint8_t> data;
};

static void writeVectorVar(std::ofstream& f,
                            const std::string& varName,
                            const std::vector<uint8_t>& data)
{
    // IIFE 包装静态数组，避免 MSVC 超大初始化列表报错
    f << "static const std::vector<uint8_t> " << varName
      << " = []() -> std::vector<uint8_t> {\n"
      << "    static const uint8_t kData[] = {\n        ";

    for (size_t i = 0; i < data.size(); ++i)
    {
        char buf[6];
        snprintf(buf, sizeof(buf), "0x%02x", data[i]);
        f << buf;
        if (i + 1 < data.size()) f << ',';
        if ((i + 1) % 16 == 0) f << "\n        ";
        else f << ' ';
    }

    f << "\n    };\n"
      << "    return std::vector<uint8_t>(kData, kData + sizeof(kData));\n"
      << "}();\n\n";
}

static bool writeHeader(const char* outPath,
                         const std::string& baseName,
                         const std::vector<KernelBlob>& blobs)
{
    std::ofstream f(outPath);
    if (!f.is_open())
    {
        fprintf(stderr, "[SlangCompiler] Cannot open output: %s\n", outPath);
        return false;
    }

    std::string guard = "SLANG_GENERATED_" + baseName + "_H";
    for (char& c : guard) c = (char)toupper((unsigned char)c);

    f << "#pragma once\n"
      << "#ifndef " << guard << "\n"
      << "#define " << guard << "\n\n"
      << "#include <vector>\n"
      << "#include <cstdint>\n\n"
      << "// Auto-generated by SlangCompiler — DO NOT EDIT\n"
      << "// Source: " << baseName << ".slang\n\n";

    for (const auto& blob : blobs)
    {
        std::string varName  = baseName + "_" + blob.targetName + "_kernel";
        std::string flagName = "SLANG_HAS_" + baseName + "_" + blob.targetName;
        for (char& c : flagName) c = (char)toupper((unsigned char)c);

        f << "// [" << blob.targetName << "] " << blob.data.size() << " bytes\n";
        f << "#define " << flagName << "\n";
        writeVectorVar(f, varName, blob.data);
    }

    f << "#endif // " << guard << "\n";
    return f.good();
}

// ── Slang 编译单个 target ─────────────────────────────────────────────────────

static std::vector<uint8_t> slangCompile(slang::ISession*    session,
                                          slang::IModule*     module,
                                          slang::IEntryPoint* ep,
                                          int                 targetIndex,
                                          Slang::ComPtr<slang::IComponentType>* outProgram = nullptr)
{
    slang::IComponentType* parts[] = { module, ep };
    Slang::ComPtr<slang::IComponentType> program;
    Slang::ComPtr<slang::IBlob> diag1;

    if (SLANG_FAILED(session->createCompositeComponentType(
            parts, 2, program.writeRef(), diag1.writeRef())))
    {
        if (diag1 && diag1->getBufferSize() > 0)
            fprintf(stderr, "%s\n", (const char*)diag1->getBufferPointer());
        return {};
    }

    if (outProgram) *outProgram = program;

    Slang::ComPtr<slang::IBlob> code, diag2;
    if (SLANG_FAILED(program->getTargetCode(targetIndex, code.writeRef(), diag2.writeRef())))
    {
        if (diag2 && diag2->getBufferSize() > 0)
            fprintf(stderr, "%s\n", (const char*)diag2->getBufferPointer());
        return {};
    }

    const auto* ptr = static_cast<const uint8_t*>(code->getBufferPointer());
    return std::vector<uint8_t>(ptr, ptr + code->getBufferSize());
}

// ── CPU 头文件生成（基于 Slang 反射）────────────────────────────────────────────

static std::string scalarTypeToCpp(slang::TypeReflection::ScalarType t)
{
    using S = slang::TypeReflection::ScalarType;
    switch (t)
    {
    case S::Bool:    return "bool";
    case S::Int8:    return "int8_t";
    case S::Int16:   return "int16_t";
    case S::Int32:   return "int32_t";
    case S::Int64:   return "int64_t";
    case S::UInt8:   return "uint8_t";
    case S::UInt16:  return "uint16_t";
    case S::UInt32:  return "uint32_t";
    case S::UInt64:  return "uint64_t";
    case S::Float16: return "uint16_t"; // half
    case S::Float32: return "float";
    case S::Float64: return "double";
    default:         return "void";
    }
}

static std::string slangTypeToCpp(slang::TypeReflection* type)
{
    if (!type) return "void*";
    switch (type->getKind())
    {
    case slang::TypeReflection::Kind::Scalar:
        return scalarTypeToCpp(type->getScalarType());
    case slang::TypeReflection::Kind::Vector:
    {
        std::string elem = scalarTypeToCpp(type->getScalarType());
        unsigned    n    = (unsigned)type->getElementCount();
        return elem + std::to_string(n);
    }
    case slang::TypeReflection::Kind::Resource:
    {
        // RWStructuredBuffer<T>: 运行时 layout 为 { T* data; size_t count; }
        // 返回元素类型，由调用方决定如何生成完整字段
        auto* res = type->getResourceResultType();
        return res ? slangTypeToCpp(res) : "void";
    }
    case slang::TypeReflection::Kind::Struct:
        return type->getName() ? type->getName() : "void*";
    default:
        return "void*";
    }
}

static bool writeCpuHeader(const char*                   outPath,
                            const std::string&            baseName,
                            const char*                   entryPoint,
                            slang::IComponentType*        program,
                            unsigned*                     outBindingCount = nullptr)
{
    slang::ProgramLayout* reflection = program->getLayout();
    if (!reflection)
    {
        fprintf(stderr, "[SlangCompiler] Cannot get reflection layout\n");
        return false;
    }

    // 线程组大小
    SlangUInt tgs[3] = { 1, 1, 1 };
    if (reflection->getEntryPointCount() > 0)
    {
        auto* ep = reflection->getEntryPointByIndex(0);
        if (ep) ep->getComputeThreadGroupSize(3, tgs);
    }

    // 全局参数结构体字段（反射）
    // isResource=true 时，生成 { T* data; size_t count; } 匹配 Slang prelude 的 RWStructuredBuffer layout
    struct ParamField {
        std::string elemType;   // 元素类型，如 "float"
        std::string name;
        bool        isResource; // 是否 RWStructuredBuffer / StructuredBuffer
    };
    std::vector<ParamField> fields;

    auto* globalVar = reflection->getGlobalParamsVarLayout();
    if (globalVar)
    {
        auto* structLayout = globalVar->getTypeLayout();
        unsigned fieldCount = (unsigned)structLayout->getFieldCount();
        for (unsigned i = 0; i < fieldCount; ++i)
        {
            auto* f    = structLayout->getFieldByIndex(i);
            auto* type = f->getType();
            std::string fname = f->getName() ? f->getName() : ("field" + std::to_string(i));
            // 去掉 Slang 生成的 _0 后缀
            if (fname.size() > 2 && fname.substr(fname.size() - 2) == "_0")
                fname = fname.substr(0, fname.size() - 2);

            bool isResource = (type->getKind() == slang::TypeReflection::Kind::Resource);
            std::string elemType = slangTypeToCpp(type); // Resource 时返回元素类型
            fields.push_back({ elemType, fname, isResource });
        }
    }

    // 统计 resource binding 数量（Vulkan descriptor binding count）
    unsigned bindingCount = 0;
    for (const auto& fld : fields)
        if (fld.isResource) ++bindingCount;
    if (outBindingCount) *outBindingCount = bindingCount;

    // ── 写出头文件 ────────────────────────────────────────────────────────────
    std::ofstream f(outPath);
    if (!f.is_open())
    {
        fprintf(stderr, "[SlangCompiler] Cannot open: %s\n", outPath);
        return false;
    }

    std::string guard = "SLANG_CPU_" + baseName + "_H";
    for (char& c : guard) c = (char)toupper((unsigned char)c);

    f << "#pragma once\n"
      << "#ifndef " << guard << "\n"
      << "#define " << guard << "\n\n"
      << "#include <cstdint>\n"
      << "#include <cstddef>\n\n"
      << "// Auto-generated CPU kernel interface — DO NOT EDIT\n"
      << "// Source: " << baseName << ".slang\n\n";

    // 线程组常量
    f << "// Thread group size\n"
      << "#define " << baseName << "_THREAD_GROUP_X " << tgs[0] << "\n"
      << "#define " << baseName << "_THREAD_GROUP_Y " << tgs[1] << "\n"
      << "#define " << baseName << "_THREAD_GROUP_Z " << tgs[2] << "\n\n";

    // 基础向量类型（仅声明一次，用 guard 保护）
    f << "#ifndef SLANG_CPU_VECTOR_TYPES\n"
      << "#define SLANG_CPU_VECTOR_TYPES\n"
      << "struct uint2 { uint32_t x, y; };\n"
      << "struct uint3 { uint32_t x, y, z; };\n"
      << "struct uint4 { uint32_t x, y, z, w; };\n"
      << "struct float2 { float x, y; };\n"
      << "struct float3 { float x, y, z; };\n"
      << "struct float4 { float x, y, z, w; };\n"
      << "#endif // SLANG_CPU_VECTOR_TYPES\n\n";

    // Compute dispatch 类型
    f << "#ifndef SLANG_CPU_DISPATCH_TYPES\n"
      << "#define SLANG_CPU_DISPATCH_TYPES\n"
      << "struct ComputeThreadVaryingInput { uint3 groupID; uint3 groupThreadID; };\n"
      << "struct ComputeVaryingInput       { uint3 startGroupID; uint3 endGroupID; };\n"
      << "#endif // SLANG_CPU_DISPATCH_TYPES\n\n";

    // 全局参数结构体
    // RWStructuredBuffer<T> 在 CPU prelude 中的 layout 是 { T* data; size_t count; }
    // kernel_Params 必须与 GlobalParams_0 完全兼容，才能直接转型传给 kernel()
    f << "// Global parameters for " << baseName << "()\n"
      << "// Layout must match Slang CPU prelude's RWStructuredBuffer<T> = { T* data; size_t count; }\n"
      << "struct " << baseName << "_Params\n{\n";
    for (const auto& fld : fields)
    {
        if (fld.isResource)
            f << "    struct { " << fld.elemType << "* data; size_t count; } "
              << fld.name << "; // RWStructuredBuffer<" << fld.elemType << ">\n";
        else
            f << "    " << fld.elemType << " " << fld.name << ";\n";
    }
    f << "};\n\n";

    // 函数声明
    f << "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";
    f << "// Single thread\n"
      << "void " << entryPoint << "_Thread("
      << "ComputeThreadVaryingInput* varyingInput, "
      << "void* entryPointParams, void* globalParams);\n\n";
    f << "// Work group (" << tgs[0] << " x " << tgs[1] << " x " << tgs[2] << " threads)\n"
      << "void " << entryPoint << "_Group("
      << "ComputeVaryingInput* varyingInput, "
      << "void* entryPointParams, void* globalParams);\n\n";
    f << "// Full dispatch (multiple groups)\n"
      << "void " << entryPoint << "("
      << "ComputeVaryingInput* varyingInput, "
      << "void* entryPointParams, void* globalParams);\n\n";
    f << "#ifdef __cplusplus\n} // extern \"C\"\n#endif\n\n";

    // 便利内联包装
    f << "#ifdef __cplusplus\n"
      << "// Convenience: dispatch with strongly-typed params\n"
      << "inline void " << entryPoint << "_dispatch(\n"
      << "    " << baseName << "_Params& params,\n"
      << "    uint32_t groupCountX, uint32_t groupCountY = 1, uint32_t groupCountZ = 1)\n"
      << "{\n"
      << "    ComputeVaryingInput vi{};\n"
      << "    vi.endGroupID = { groupCountX, groupCountY, groupCountZ };\n"
      << "    " << entryPoint << "(&vi, nullptr, &params);\n"
      << "}\n"
      << "#endif // __cplusplus\n\n";

    f << "#endif // " << guard << "\n";
    return f.good();
}

// ── KernelFactory 特化头文件（kernel_factory.h）──────────────────────────────
// 生成 skl::KernelFactory<SlangKernelID::<name>, Backend> 特化。
// 此文件必须在 SlangKernelID 枚举定义之后被 include（由 slang_kernels.h 保证）。

static bool writeFactoryHeader(const char*        outPath,
                                const std::string& baseName,
                                unsigned           bindingCount)
{
    std::ofstream f(outPath);
    if (!f.is_open())
    {
        fprintf(stderr, "[SlangCompiler] Cannot open: %s\n", outPath);
        return false;
    }

    std::string guard = "SLANG_FACTORY_" + baseName + "_H";
    for (char& c : guard) c = (char)toupper((unsigned char)c);

    std::string nameUpper = baseName;
    for (char& c : nameUpper) c = (char)toupper((unsigned char)c);

    f << "#pragma once\n"
      << "#ifndef " << guard << "\n"
      << "#define " << guard << "\n\n"
      << "// Auto-generated KernelFactory specializations — DO NOT EDIT\n"
      << "// Source: " << baseName << ".slang\n"
      << "// NOTE: SlangKernelID must be defined before including this file (provided by slang_kernels.h)\n\n"
      << "#include \"SlangKernelLauncher.h\"\n"
      // VulkanBackend.h must be included BEFORE namespace skl to avoid skl::skl:: nesting
      << "#if defined(SKL_HAS_VULKAN)\n"
      << "#include \"VulkanBackend.h\"\n"
      << "#endif\n\n"
      << "namespace skl {\n\n"
      // CPU specialization — always present (cpp target is always compiled)
      << "template<>\n"
      << "struct KernelFactory<SlangKernelID::" << baseName << ", CPU> {\n"
      << "    static CPUFunction get() { return toCPUFunction(::" << baseName << "_Group); }\n"
      << "};\n\n"
      // CUDA specialization — conditional on Driver API + CUDA blob
      << "#if defined(SKL_HAS_CUDA_DRIVER) && defined(SLANG_HAS_" << nameUpper << "_CUDA)\n"
      << "template<>\n"
      << "struct KernelFactory<SlangKernelID::" << baseName << ", CUDA> {\n"
      << "    // Returns a CUDAFunction; check .module != nullptr for success\n"
      << "    static CUDAFunction get() {\n"
      << "        CUDAFunction fn{};\n"
      << "        loadCUDAFunction(::" << baseName << "_cuda_kernel, \""
      << baseName << "\", fn);\n"
      << "        return fn;\n"
      << "    }\n"
      << "};\n"
      << "#endif\n\n"
      // Vulkan specialization — conditional on Vulkan SDK + SPIR-V blob
      << "#if defined(SKL_HAS_VULKAN) && defined(SLANG_HAS_" << nameUpper << "_VULKAN)\n"
      << "template<>\n"
      << "struct KernelFactory<SlangKernelID::" << baseName << ", Vulkan> {\n"
      << "    // Returns a VulkanFunction; check .pipeline != VK_NULL_HANDLE for success\n"
      << "    static VulkanFunction get(const VulkanContext& ctx) {\n"
      // Slang always renames the entry point to "main" when targeting SPIR-V
      << "        return loadVulkanFunction(::" << baseName << "_vulkan_kernel, ctx, "
      << bindingCount << "u, \"main\");\n"
      << "    }\n"
      << "};\n"
      << "#endif\n\n"
      << "} // namespace skl\n\n"
      << "#endif // " << guard << "\n";

    return f.good();
}

// ── main ──────────────────────────────────────────────────────────────────────

struct TargetSpec
{
    const char*        name;
    SlangCompileTarget format;
    const char*        profile;  // "" 表示不指定
};

int main(int argc, char* argv[])
{
    if (argc < 3)
    {
        fprintf(stderr,
            "Usage: SlangCompiler <input.slang> <output.h>"
            " [entryPoint=computeMain] [cudaArch=sm_80]\n");
        return EXIT_FAILURE;
    }

    const char* inputPath  = argv[1];
    const char* outputPath = argv[2];
    const char* cudaArch   = argc > 4 ? argv[4] : "sm_80";

    // 默认用文件名（不含扩展）作为入口函数名，保持 <name>.slang → <name>() 的一致性
    // CMake 编译时会显式传入 argv[3]；手动调用时若省略则自动推断
    std::string entryPointStr;
    if (argc > 3)
    {
        entryPointStr = argv[3];
    }
    else
    {
        std::string tmp = inputPath;
        size_t s = tmp.find_last_of("/\\");
        entryPointStr = (s == std::string::npos) ? tmp : tmp.substr(s + 1);
        size_t d = entryPointStr.rfind('.');
        if (d != std::string::npos) entryPointStr = entryPointStr.substr(0, d);
    }
    const char* entryPoint = entryPointStr.c_str();

    // ── 根据 CMake 检测结果决定编译哪些 target ────────────────────────────────
    // 所有判断在编译期通过 #ifdef 完成，不在运行时做任何环境探测
    std::vector<TargetSpec> targets;

#ifdef SLANG_COMPILER_HAS_VULKAN
    targets.push_back({ "vulkan", SLANG_SPIRV,       "spirv_1_5" });
#endif

#ifdef SLANG_COMPILER_HAS_METAL
    targets.push_back({ "metal",  SLANG_METAL,       ""          });
#endif

#ifdef SLANG_COMPILER_HAS_CUDA
    targets.push_back({ "cuda",   SLANG_CUDA_SOURCE, "sm_80"     });
#endif

    // C++ source：始终输出，不依赖任何外部工具
    targets.push_back({ "cpp", SLANG_CPP_SOURCE, "" });

    fprintf(stdout, "[SlangCompiler] Active targets:");
    for (const auto& t : targets) fprintf(stdout, " %s", t.name);
    fprintf(stdout, "\n");

    // ── 初始化 Slang session（一次 session 含所有 target）────────────────────
    Slang::ComPtr<slang::IGlobalSession> globalSession;
    if (SLANG_FAILED(slang::createGlobalSession(globalSession.writeRef())))
    {
        fprintf(stderr, "[SlangCompiler] Failed to create global session\n");
        return EXIT_FAILURE;
    }

    std::vector<slang::TargetDesc> targetDescs(targets.size());
    for (size_t i = 0; i < targets.size(); ++i)
    {
        targetDescs[i]         = {};
        targetDescs[i].format  = targets[i].format;
        targetDescs[i].profile = targets[i].profile[0]
                                 ? globalSession->findProfile(targets[i].profile)
                                 : SlangProfileID(0);
    }

    slang::SessionDesc sessionDesc{};
    sessionDesc.targets     = targetDescs.data();
    sessionDesc.targetCount = (SlangInt)targetDescs.size();

    Slang::ComPtr<slang::ISession> session;
    if (SLANG_FAILED(globalSession->createSession(sessionDesc, session.writeRef())))
    {
        fprintf(stderr, "[SlangCompiler] Failed to create session\n");
        return EXIT_FAILURE;
    }

    // ── 加载 .slang 模块 ──────────────────────────────────────────────────────
    Slang::ComPtr<slang::IModule> module;
    {
        Slang::ComPtr<slang::IBlob> diag;
        module = session->loadModule(inputPath, diag.writeRef());
        if (diag && diag->getBufferSize() > 0)
            fprintf(stderr, "%s\n", (const char*)diag->getBufferPointer());
        if (!module)
        {
            fprintf(stderr, "[SlangCompiler] Failed to load: %s\n", inputPath);
            return EXIT_FAILURE;
        }
    }

    Slang::ComPtr<slang::IEntryPoint> ep;
    if (SLANG_FAILED(module->findEntryPointByName(entryPoint, ep.writeRef())))
    {
        fprintf(stderr, "[SlangCompiler] Entry point '%s' not found\n", entryPoint);
        return EXIT_FAILURE;
    }

    // ── 取文件名作为变量前缀 ──────────────────────────────────────────────────
    std::string inputStr = inputPath;
    size_t slash = inputStr.find_last_of("/\\");
    std::string baseName = slash == std::string::npos ? inputStr : inputStr.substr(slash + 1);
    size_t dot = baseName.rfind('.');
    if (dot != std::string::npos) baseName = baseName.substr(0, dot);

    // ── 逐 target 编译 ────────────────────────────────────────────────────────
    std::vector<KernelBlob> blobs;

    // cpp target 输出路径：将 output.h 的后缀换成 _cpu.cpp
    std::string cpuCppPath = outputPath;
    {
        size_t dot = cpuCppPath.rfind('.');
        if (dot != std::string::npos) cpuCppPath = cpuCppPath.substr(0, dot);
        cpuCppPath += "_cpu.cpp";
    }

    for (int i = 0; i < (int)targets.size(); ++i)
    {
        const auto& spec = targets[i];
        fprintf(stdout, "[SlangCompiler] Compiling -> %s ...\n", spec.name);

        auto data = slangCompile(session, module, ep, i);
        if (data.empty())
        {
            fprintf(stderr, "[SlangCompiler] Warning: %s slang compile failed, skipped\n", spec.name);
            continue;
        }

        // cpp target：写成独立 .cpp + 对应 .h，供 CPU 端编译调试，不嵌入头文件
        if (strcmp(spec.name, "cpp") == 0)
        {
            // 写 .cpp 实现文件，末尾追加对 _cpu.h 的 include，以便编译器验证签名一致
            // Slang prelude 已定义 uint3/ComputeVaryingInput 等，先 define guard 跳过重复定义
            {
                std::ofstream cpuFile(cpuCppPath, std::ios::binary);
                if (!cpuFile.is_open())
                {
                    fprintf(stderr, "[SlangCompiler] Warning: cannot write %s\n", cpuCppPath.c_str());
                    continue;
                }
                cpuFile.write(reinterpret_cast<const char*>(data.data()), data.size());

                // 取头文件的文件名（不含目录），让 #include 使用相对路径
                std::string cpuHeaderName = baseName + "_cpu.h";
                cpuFile << "\n"
                        << "// Include our interface header to let the compiler verify signatures.\n"
                        << "// The Slang prelude already defines vector/dispatch types, so suppress them.\n"
                        << "#define SLANG_CPU_VECTOR_TYPES\n"
                        << "#define SLANG_CPU_DISPATCH_TYPES\n"
                        << "#include \"" << cpuHeaderName << "\"\n";
            }

            // 写 .h 接口头文件（基于 Slang 反射）
            Slang::ComPtr<slang::IComponentType> cpuProgram;
            slangCompile(session, module, ep, i, std::addressof(cpuProgram));
            std::string cpuHeaderPath    = cpuCppPath.substr(0, cpuCppPath.rfind('.')) + ".h";
            // factory header: derived from outputPath (kernel.h -> kernel_factory.h)
            std::string factoryHeaderPath = outputPath;
            {
                size_t d = factoryHeaderPath.rfind('.');
                if (d != std::string::npos) factoryHeaderPath = factoryHeaderPath.substr(0, d);
                factoryHeaderPath += "_factory.h";
            }
            unsigned bindingCount = 0;
            writeCpuHeader(cpuHeaderPath.c_str(), baseName, entryPoint, cpuProgram, &bindingCount);
            writeFactoryHeader(factoryHeaderPath.c_str(), baseName, bindingCount);

            fprintf(stdout, "[SlangCompiler]   cpp (CPU): %s + %s + %s (%zu bytes)\n",
                    cpuCppPath.c_str(),
                    cpuHeaderPath.c_str(),
                    factoryHeaderPath.c_str(),
                    data.size());
            continue;  // 不加入 blobs，不写进头文件
        }

#ifdef SLANG_COMPILER_HAS_CUDA
        // CUDA：Slang 输出 CUDA source，再用 NVRTC 编译成 PTX
        if (strcmp(spec.name, "cuda") == 0)
        {
            fprintf(stdout, "[SlangCompiler]   NVRTC -> PTX (arch=%s) ...\n", cudaArch);
            auto ptx = compileToPTX(data, cudaArch);
            if (ptx.empty())
            {
                fprintf(stderr, "[SlangCompiler] Warning: NVRTC PTX compile failed, skipped\n");
                continue;
            }
            data = std::move(ptx);
        }
#endif

        fprintf(stdout, "[SlangCompiler]   %s: %zu bytes\n", spec.name, data.size());
        blobs.push_back({ spec.name, std::move(data) });
    }

    if (blobs.empty())
    {
        fprintf(stderr, "[SlangCompiler] No targets succeeded\n");
        return EXIT_FAILURE;
    }

    // ── 写出头文件 ────────────────────────────────────────────────────────────
    if (!writeHeader(outputPath, baseName, blobs))
        return EXIT_FAILURE;

    fprintf(stdout, "[SlangCompiler] Done: %s\n", outputPath);
    return EXIT_SUCCESS;
}
